### ISSUE TITLE
Feature Request: Remote Images

### ISSUE THREAD

**Issue by yinkakun** [Halo-Lab/eleventy-shortcode-image#1]
Hi, Great Work!

I'm wondering if this plugin supports or has a plan to support remote images.
So that I can just pass the image link from an API response.

Thanks in advance.

**Comment by Kapelianovych** [comment]
Hello! Thank you for your issue. Yes, plugin can download remote images and add them into HTML. If you find an issue feel free to report it here)

**Comment by yinkakun** [comment]
Great. Thanks.
